[package]
name = "service-runtime-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
service-runtime-core = { path = "../service-runtime-core" }
service-runtime-state = { path = "../service-runtime-state" }
sp-trie = { version = "=46.0.0", default-features = false, features = ["std"] }
