[package]
name = "jamscript-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jamscript-crypto = { path = "../jamscript-crypto" }
jamscript-protocol = { path = "../jamscript-protocol" }
ownership-core = { path = "../ownership-core" }
service-runtime-core = { path = "../service-runtime-core" }
