[package]
name = "jamscript-service-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
bounded-collections.workspace = true
clap.workspace = true
jam-codec.workspace = true
jam-program-blob-common.workspace = true
jamscript-deployment = { path = "../jamscript-deployment" }
jamscript-runtime-core = { path = "../jamscript-runtime-core" }
parity-scale-codec.workspace = true
polkavm.workspace = true
polkavm-linker.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
service-runtime-core = { path = "../service-runtime-core" }
service-runtime-host = { path = "../service-runtime-host" }
service-runtime-state = { path = "../service-runtime-state" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
